
[tasks.rpi4]
env = { "RUSTFLAGS" = "-C link-arg=-Tsrc/bsp/rpi4/link.ld -C target-cpu=cortex-a53 -D warnings -D missing_docs" } 
command = "cargo"
args = ["rustc", "--target=aarch64-unknown-none-softfloat", "--features=rpi4"]


[tasks.qemu]
script = { file = "scripts/qemu-rpi-run.sh" }



