[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = ".targets/x86_64-walnut.json"


[target.'cfg(target_os = "none")']
runner = "bootimage runner --quiet"
