name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly and misc components 
      run: rustup target add aarch64-unknown-none-softfloat && cargo install cargo-binutils
    - name: Build for Raspberry Pi 4
      run: make
    - name: Build for Raspberry Pi 3
      run: BSP=rpi3 make
