name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install UEFI Target
      run: rustup target add x86_64-unknown-uefi
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo clippy 
      # TODO run `cargo test --verbose` once tests are implemented
