name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly and `rust-src`
      run: rustup install nightly && rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo +nightly build -Z build-std
    - name: Run tests
      run: cargo clippy 
      # TODO run `cargo test --verbose` once tests are implemented
